
name: CI

on:
  workflow_dispatch: # manually trigger workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: poetry run pytest
